
services:
  kib01:
    container_name: kib01
    image: docker.elastic.co/kibana/kibana:8.14.3
    labels:
      co.elastic.logs/module: kibana
    # volumes:
    #   - kibanadata:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=${ELASITC_HOST}
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    networks:
      - elastic

networks:
  elastic:
    external: true

# volumes:
#   kibanadata:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /mnt/sda/kibanadata